Repository JIA-Team5-ReactProject/2023-DiaryApp-Team5-FE, pull requests merged in 2023-12, with the labels that each got.

#46 Fix: diaryCard 기본 이미지 적용
  src/components/DiaryCard.js
Labels: ✨ Feat, 🐛 Fix

#47 Feat: Add logic to delete posts when a member withdraws etc
  src/components/Comments.js
  src/components/DiaryValue.js
  src/components/SetAccount.js
  src/hooks/S3Uploader.js
Labels: 🔨 Chore, 🎨 Design, ✨ Feat

#49 fix: Bug Fix in DiaryCard within MyPage
  src/pages/MyPage.js
Labels: 🐛 Fix

#50 Chore: Port number change
  package.json
  src/components/DiaryValue.js
  src/components/Profile.js
  src/components/SetAccount.js
  src/components/WriteCard.js
  src/services/AuthService.js
  src/services/CommentService.js
  src/services/DiaryService.js
  src/services/SearchService.js
Labels: 🔨 Chore
