Repository JIA-Team5-ReactProject/2023-DiaryApp-Team5-FE, pull requests merged in 2023-11, with the labels that each got.

#21 Feat : Implement search logic
  .gitignore
  package-lock.json
  package.json
  src/components/DiaryCard.js
  src/components/searchbar/SearchBar.jsx
  src/components/searchbar/SearchInput.jsx
  src/database/db.json
  src/pages/Every.js
  src/pages/Me.js
  src/services/InfiniteScrollService.js
  src/services/SearchService.js
  src/store/recoil.js
  src/util/getPost.js
Labels: 🔨 Chore, ✨ Feat

#23 Feat: 일기 작성 기능 추가
  .gitignore
  .vscode/launch.json
  package.json
  public/index.html
  src/App.js
  src/components/WriteCard.js
  src/database/db.json
  src/pages/Main.js
  src/pages/Write.js
Labels: ✨ Feat

#25 Feat: Set a default profile image for registration etc
  package-lock.json
  package.json
  src/assets/default.png
  src/components/AuthForm.js
  src/components/Profile.js
  src/components/SetAccount.js
  src/hooks/S3Uploader.js
  src/store/recoil.js
  tailwind.config.js
Labels: 🔨 Chore, ✨ Feat

#27 Feat: 일기 작성 기능 구현
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/WriteCard.js
  src/pages/Main.js
  src/pages/Write.js
Labels: ✨ Feat

#30 fix: Fix err
  db.json
  package-lock.json
  src/App.js
  src/components/Comments 삭제기능 전.js
  src/components/Comments.js
  src/components/DiaryCard.js
  src/components/DiaryModal.js
  src/components/DiaryValue.js
  src/pages/Account.js
  src/pages/Diary.js
  src/pages/Every.js
  src/pages/Me.js
  src/pages/MyPage.js
  src/services/AuthService.js
  src/services/CommentService.js
  src/services/DiaryService.js
  src/services/InfiniteScrollService.js
  src/services/LogoutService.js
  src/services/SearchService.js
Labels: 🐛 Fix

#31 Feat: Create teammate page & mate components
  package-lock.json
  src/App.js
  src/components/DiaryCard.js
  src/components/Header.js
  src/components/Mate.js
  src/pages/Every.js
  src/pages/Me.js
  src/pages/Teammate.js
Labels: 🎨 Design, ✨ Feat

#32 Fix: fix search logic
  src/components/DiaryCard.js
  src/components/Mate.js
  src/components/searchbar/SearchBar.jsx
  src/pages/Every.js
  src/pages/Teammate.js
  src/services/SearchService.js
Labels: ✨ Feat, 🐛 Fix

#34 Fix: fix mypage search error
  src/pages/MyPage.js
Labels: 🐛 Fix
